# Generated by Django 3.2.5 on 2021-07-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_withdraw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='location',
            new_name='province',
        ),
        migrations.AddField(
            model_name='influencer',
            name='city',
            field=models.CharField(default='---', max_length=25),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
