# Generated by Django 3.2.5 on 2021-07-05 11:25

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_marketer_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='marketer',
            managers=[
                ('objects', users.managers.MarketerManager()),
            ],
        ),
    ]
