# Generated by Django 3.2.5 on 2021-07-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210728_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='city',
            field=models.CharField(max_length=25),
        ),
    ]
