# Generated by Django 3.2.5 on 2021-07-21 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('is_video', models.BooleanField()),
                ('image', models.FileField(upload_to='')),
                ('video', models.FileField(blank=True, upload_to='')),
                ('base_link', models.CharField(max_length=60)),
                ('clicks', models.IntegerField(default=0)),
                ('max_budget', models.PositiveIntegerField()),
                ('is_general', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.marketer')),
                ('topics', models.ManyToManyField(related_name='Ads', to='users.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('suggest_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.ad')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.influencer')),
            ],
        ),
        migrations.CreateModel(
            name='InfAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(default=0)),
                ('short_link', models.CharField(blank=True, max_length=7)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('suggest_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.suggestad')),
            ],
        ),
    ]
