# Generated by Django 3.2.5 on 2021-07-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infad',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.influencer'),
        ),
        migrations.AddField(
            model_name='ad',
            name='marketer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.marketer'),
        ),
        migrations.AddField(
            model_name='ad',
            name='topics',
            field=models.ManyToManyField(related_name='Ads', to='users.Topic'),
        ),
    ]
