# Generated by Django 3.2.5 on 2021-07-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infad',
            old_name='suggest_ad',
            new_name='suggested_ad',
        ),
        migrations.RenameField(
            model_name='suggestad',
            old_name='suggest_at',
            new_name='suggested_at',
        ),
    ]
