# Generated by Django 3.2.5 on 2021-07-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestad',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
