# Generated by Django 3.2.5 on 2021-07-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('ad', '0002_auto_20210721_1401'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='suggestad',
            unique_together={('ad', 'influencer')},
        ),
    ]
