# Generated by Django 3.2.5 on 2021-07-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_alter_infad_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infad',
            name='short_link',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
