# Generated by Django 3.2.5 on 2021-07-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_suggestad_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestad',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suggestad',
            name='report_msg',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
