# Generated by Django 3.2.5 on 2021-07-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_withdraw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Withdraw',
        ),
    ]
